[[main]]
identifier = "home"
name = "阅览大厅"
pageRef = "/"
weight = 10

  [main.params]
  code = "00"
  sections = []

[[main]]
identifier = "geography"
name = "国家与地区"
pageRef = "/portals/geography"
weight = 20

  [main.params]
  code = "01"
  sections = ["nations", "regions"]

[[main]]
identifier = "characters-organizations"
name = "人物与组织"
pageRef = "/portals/characters-organizations"
weight = 30

  [main.params]
  code = "02"
  sections = ["characters", "organizations"]

[[main]]
identifier = "history"
name = "历史与年代"
pageRef = "/portals/history"
weight = 40

  [main.params]
  code = "03"
  sections = ["history"]

[[main]]
identifier = "concepts-records"
name = "概念与档案"
pageRef = "/portals/concepts-records"
weight = 50

  [main.params]
  code = "04"
  sections = ["concepts", "artifacts", "records"]

[[main]]
identifier = "ecology"
name = "生态与物种"
pageRef = "/portals/ecology"
weight = 60

  [main.params]
  code = "05"
  sections = ["ecology"]

[[main]]
identifier = "timeline"
name = "世界时间线"
pageRef = "/timeline"
weight = 70

  [main.params]
  code = "06"
  sections = ["timeline"]

[[main]]
identifier = "search"
name = "检索中心"
pageRef = "/search"
weight = 80

  [main.params]
  code = "07"
  sections = ["search"]
